version: '3.8'

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: brasileirao-db
    environment:
      POSTGRES_USER: brasileirao
      POSTGRES_PASSWORD: brasileirao2026
      POSTGRES_DB: brasileirao_2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/create_database.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U brasileirao -d brasileirao_2026" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - brasileirao-net

  # Redis Broker
  redis:
    image: redis:7-alpine
    container_name: brasileirao-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - brasileirao-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # API Hub
  api:
    build: .
    container_name: brasileirao-api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://brasileirao:brasileirao2026@db:5432/brasileirao_2026
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - brasileirao-net

volumes:
  postgres_data:
  redis_data:


networks:
  brasileirao-net:
    driver: bridge
